PARAMETERS:
  one_hot_map_builder: WithOutageOneHotMapBuilder
  network_transition_handler: WithOutageNetworkTransitionHandler
  network_snapshot_builder: WithOutageNetworkSnapshotObservationBuilder
  outage_handler_config:
    line1:
      initial_outage_prob: 0
      initial_remaining_duration: 0
      initial_usage_time: 0
      lambda_factor: 0.0001
      seed: 0
    line2:
      initial_outage_prob: 0
      initial_remaining_duration: 0
      initial_usage_time: 0
      lambda_factor: 0.0001
      seed: 0
